name: Send Email on Push to Master

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send email using GitHub API
      uses: actions/github-script@v7
      with:
        script: |
          const email = 'saurang1984@gmail.com';
          const subject = 'Code Pushed to Master Branch';
          const body = `Code has been pushed to the master branch by ${context.actor}.`;

          const result = await github.request('POST /repos/{owner}/{repo}/dispatches', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'send-email',
            client_payload: {
              email: email,
              subject: subject,
              body: body
            },
            headers: {
              authorization: `token ${process.env.EMAIL_PAT}`
            }
          });

          console.log(result);
    env:
      PAT: ${{ secrets.EMAIL_PAT }}
