name: Dynamic Environment Variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'DEV'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set dynamic environment variable
      id: set-secret
      run: |
        case ${{ inputs.environment }} in
          PROD) echo "ORG_SECRET=${{ secrets.PROD_secret }}" >> $GITHUB_ENV ;;
          DEV) echo "ORG_SECRET=${{ secrets.DEV_secret }}" >> $GITHUB_ENV ;;
          TEST) echo "ORG_SECRET=${{ secrets.TEST_secret }}" >> $GITHUB_ENV ;;
        esac

    - name: Use dynamic environment variable
      run: echo "The secret is $ORG_SECRET"

    - name: Compare secret
      id: compare-secret
      run: |
        if [ "$ORG_SECRET" = "Dev" ]; then
          echo "MATCH=true" >> $GITHUB_ENV
        else
          echo "MATCH=false" >> $GITHUB_ENV
        fi

    - name: Output comparison result
      run: echo "Secret match result $MATCH"
